name: Java CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: build and test cadc-tap
      run: cd cadc-tap && ../gradlew --info clean build javadoc install

    - name: build and test cadc-tap-schema
      run: cd cadc-tap-schema && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-tap-server
      run: cd cadc-tap-server && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-tap-server-pg
      run: cd cadc-adql && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-tap-server-oracle
      run: cd cadc-adql && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-jsqlparser-compat
      run: cd cadc-jsqlparser-compat && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-adql
      run: cd cadc-adql && ../gradlew --info clean build javadoc install
      
    - name: build and test cadc-test-tap
      run: cd cadc-test-tap && ../gradlew --info clean build javadoc install

    - name: build example-tap
      run: cd example-tap && ../gradlew --info clean build
    
